DROP TABLE rm_server CASCADE CONSTRAINTS;
DROP TABLE rm_table CASCADE CONSTRAINTS;
DROP TABLE rm_reservation CASCADE CONSTRAINTS;


CREATE TABLE rm_server (
name_server VARCHAR2(100) NOT NULL,
id VARCHAR2(5) CONSTRAINT SERV_ID_PK PRIMARY KEY,
password VARCHAR2(8) CONSTRAINT SERV_PSW_UK UNIQUE
);

CREATE TABLE rm_table (
table_num NUMBER(2) PRIMARY KEY
);

CREATE TABLE rm_reservation (
reservation_code VARCHAR2(7),
name_customer VARCHAR(100) NOT NULL,
time TIMESTAMP NOT NULL,
num_guest INT NOT NULL,
id VARCHAR2(5),
table_num INT,
status VARCHAR2(10),
CONSTRAINT RESERV_FK1 FOREIGN KEY (id) REFERENCES rm_server(id),
CONSTRAINT RESERV_FK2 FOREIGN KEY (table_num) REFERENCES rm_table(table_num)
);